### ISSUE TITLE
Speech to text throws 500 status code

### ISSUE THREAD

**Issue by elayabharath** [watson-developer-cloud/speech-to-text-nodejs#194]
I'm trying to transcribe an audio of length ~1 hour 40 mins. Audio format in FLAC of size ~160mb.

I keep getting a server error which is not very useful in understanding what is going on.

```
Error: { Error: Server Error
    at Request._callback (/Users/eb/Documents/speech-to-text-api/node_modules/watson-developer-cloud/lib/requestwrapper.js:102:21)
    at Request.self.callback (/Users/eb/Documents/speech-to-text-api/node_modules/watson-developer-cloud/node_modules/request/request.js:185:22)
    at Request.emit (events.js:127:13)
    at Request.<anonymous> (/Users/eb/Documents/speech-to-text-api/node_modules/watson-developer-cloud/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:127:13)
    at IncomingMessage.<anonymous> (/Users/eb/Documents/speech-to-text-api/node_modules/watson-developer-cloud/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  code: 500,
  error: 'Server Error',
  description: '2018-06-02T20:52:00-05:00, Error WATSNGWERR-0x0113001c occurred when accessing https://stream.watsonplatform.net/speech-to-text/api/v1/recognitions?word_confidence=true&amp;timestamps=true, Tran-Id: stream01-1550903869 - Watson Gateway Error',
  'x-global-transaction-id': undefined }
```

Code as follows
```
var SpeechToTextV1 = require("watson-developer-cloud/speech-to-text/v1");
var fs = require("fs");

var speech_to_text = new SpeechToTextV1({
  username: process.env.IBM_USER,
  password: process.env.IBM_PASSWORD
});

 var params = {
    content_type: "audio/flac",
    audio: fs.createReadStream(__dirname + "/audio.flac"),
    timestamps: true,
    word_confidence: true
  };

  speech_to_text.createJob(params, function(error, job) {
    if (error) console.log("Error:", error);
    else console.log(JSON.stringify(job, null, 2));
  });
```

**Comment by germanattanasio** [comment]
The service has a limit of 100mb for a single file.

**Comment by elayabharath** [comment]
Got it! Would you guys be able to add appropriate error codes? that will be sure helpful
