### ISSUE TITLE
speech-to-text (IAM) does not work in US East.

### ISSUE THREAD

**Issue by takahashi-jiec** [watson-developer-cloud/speech-to-text-nodejs#212]
**Describe the bug**
Speech recognition does not work

**To Reproduce**
1. Change .env
2. Start node.js
3. Access URL

The procedure is as follows
https://github.com/watson-developer-cloud/speech-to-text-nodejs

```
[root@localhost speech-to-text-nodejs]# npm start

> @ibm-watson/speech-to-text-nodejs@2.2.0 start /root/STT/speech-to-text-nodejs
> node server.js

listening at: 3000
Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (/root/STT/speech-to-text-nodejs/node_modules/watson-developer-cloud/lib/requestwrapper.ts:106:15)
    at Request.self.callback (/root/STT/speech-to-text-nodejs/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/STT/speech-to-text-nodejs/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/STT/speech-to-text-nodejs/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Expected behavior**
Authentication does not pass

**Screenshots**
<img width="1278" alt="2018-10-26 14 14 48" src="https://user-images.githubusercontent.com/27751616/47545896-a9c5d000-d929-11e8-9d20-8b6c6de08a61.png">
<img width="1279" alt="2018-10-26 14 15 04" src="https://user-images.githubusercontent.com/27751616/47545897-aa5e6680-d929-11e8-94ff-00b1ec097b83.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser FireFox
 - Version 63.0

**Comment by takahashi-jiec** [comment]
I'm sorry I moved.
